### ISSUE TITLE
req.checkHeader with optional() doesnt work

### ISSUE THREAD

**Issue by avivshaked** [ctavan/express-validator#113]
req.checkHeader will return the value or an empty string:
> return toCheck || '';

and optional checks only against undefined:
> if (value !== undefined)

value will never be undefined for checkHeader, and so this validation fails when the header is not provided even with optional()

**Comment by rustybailey** [comment]
Seems like an easy fix would be to go into this section (https://github.com/ctavan/express-validator/blob/master/lib/express_validator.js#L195-L204) and change `return toCheck || '';` to `return req.headers && toCheck;` so that the output mirrors that of the other check* methods. A simple test showed that this would allow `optional()` to work.

@ctavan Can you think of any way this change would create problems for existing code? If not, I'll create a PR.

**Comment by ctavan** [comment]
@rustybailey Sounds good! Go for it!
