### ISSUE TITLE
New Maintainer

### ISSUE THREAD

**Issue by ctavan** [ctavan/express-validator#124]
Since I cannot offer enough support for this project I'm looking for a new maintainer. If you feel you can continue support for this project please get in touch!

**Comment by jonathandelgado** [comment]
@ctavan I'd be more than happy.

**Comment by rustybailey** [comment]
I have contacted @ctavan and stepped up to this role. Over the next week, I'll be going through issues and closing outdated suggestions or answered questions, and labeling the remaining issues with something like feature or bug so we can organize before taking action on what is out there.

If anyone can help out by commenting on issues that should be closed (bugs/features that have already been resolved or questions that have already been answered sufficiently), that would be helpful. Otherwise, I'll get to it as I have free time.

I'll leave this issue open for a few days so anyone that stops by can see it.

**Comment by ctavan** [comment]
@rustybailey thank you so much for taking over!

**Comment by ctavan** [comment]
Closing this for now since @rustybailey is doing a great job here!
