### ISSUE TITLE
isDate()

### ISSUE THREAD

**Issue by chrisvdb** [ctavan/express-validator#146]
Hi,

I hope somebody can help me figure out what I'm doing wrong:

    req.checkBody('profile.dateOfBirth', 'Date of birth needs to be a valid date').isDate({format: 'DD-MM-YYYY'});

Yields the following validation error:

    {
        "param": "profile.dateOfBirth",
        "msg": "Date of birth needs to be a valid date",
        "value": "22-06-1977"
    }

I tried with different format strings, no format string, etc but the result is always the same. All other validations (notEmpty, isAlpha, len, etc) on other params work as expected only isDate consistently fails.

**Comment by rustybailey** [comment]
express-validator is simply a middleware wrapper of [validator.js](https://github.com/chriso/validator.js), so all available validators are listed on their README. Just looking at their docs/code, the `isDate` method does not accept an object for specifying a format. Behind the scenes, [this is how it is validated](https://github.com/chriso/validator.js/blob/37e8ee46d87ddbac5f837708b0b7ee6fc0abbf74/validator.js#L429-L431):
```js
    validator.isDate = function (str) {
        return !isNaN(Date.parse(str));
    };
```

So in order for `isDate` to work, you will either need to:
1. Remove the object when calling it.
2. Create a PR to validator.js so that the format functionality works.
3. Create a custom validator that checks for that format using regex or [moment.js](http://momentjs.com/docs/)'s `isValid()`.

Let me know if this works. If so, please close the issue.

**Comment by chrisvdb** [comment]
Thanks, Rusty. I'll make a custom validator in that case.

**Comment by afrikhero** [comment]
A custom validator does work for form. isDate() seems deprecated and removed from express-validator.

**Comment by Pedro-Sousa-da-Rocha** [comment]
Today what is the best way to validate a date??

**Comment by gustavohenke** [comment]
Hi @afrikhero @Pedro-Sousa-da-Rocha, `isISO8601` is probably the best method from [validator](https://github.com/chriso/validator.js) to validate dates.

**Comment by Pedro-Sousa-da-Rocha** [comment]
Thanks, helped a lot!!!!

**Comment by sant123** [comment]
Ey @gustavohenke, is it really `isDate()` deprecated? If it does we should remove these lines:

https://github.com/ctavan/express-validator/blob/master/check/schema.d.ts#L45
https://github.com/ctavan/express-validator/blob/master/index.d.ts#L88

Glad to make a PR.

**Comment by sant123** [comment]
However how should we handle this? 
https://github.com/ctavan/express-validator/issues/542

`isISO8601` + `toDate` = 💔

**Comment by sant123** [comment]
For now this is my workaround:

```js
dateOfBirth: {
    in: ["body"],
    custom: {
        options: (value: Date) => !!value && validator.isISO8601(value.toISOString()),
        errorMessage: "The 'dateOfBirth' field must follow the standard ISO 8601",
    },
    toDate: true,
},
```

**Comment by gustavohenke** [comment]
Hey @sant123, yes, TypeScript's `isDate` should go!

**Comment by sant123** [comment]
Please see https://github.com/ctavan/express-validator/pull/557
