### ISSUE TITLE
Shrinkwrap breaks after recent lodash (3.10.0) release

### ISSUE THREAD

**Issue by paambaati** [ctavan/express-validator#150]
After updating lodash to `3.10.0`, `npm shrinkwrap` throws an error as express-validator depends on `3.9.3`. Would you mind bumping lodash? The [changelog](https://github.com/lodash/lodash/commit/f2d87df120c6a675d358f66b37b01adc637cbe55) doesn't list any breaking changes.

**Comment by rustybailey** [comment]
This fix is now on 2.13.0 and should be on npm shortly (10-15 mins).

**Comment by paambaati** [comment]
Thanks a bunch!

![You da real MVP](http://i.imgur.com/14lYHcU.gif)

**Comment by paambaati** [comment]
@rustybailey Same for lodash 3.10.1 now. Can you probably use `3.10.x`?

**Comment by rustybailey** [comment]
While using 3.10.x is most likely safe, I'd rather use strict versions so that we know exactly what the package depends on. Also, is there any reason that lodash needs to be updated? With the versions for our dependencies being locked, it shouldn't need to be updated unless there is a bug or we need a new feature they are offering.

**Comment by paambaati** [comment]
@rustybailey It's just that I have a project and it has many dependencies that all use lodash. I suspect one of them uses 3.10.x, because I can't create my shrinkwrap file because of this error now.

```
warn unmet dependency /project/node_modules/express-validator requires lodash@'3.10.0' but will load
warn unmet dependency /project/node_modules/lodash,
warn unmet dependency which is version 3.10.1
```

**Comment by rustybailey** [comment]
Changed lodash to 3.10.x in version 2.14.0. Should be live on npm soon.
