### ISSUE TITLE
isMongoId doesn't work in version 2.7.0

### ISSUE THREAD

**Issue by honglio** [ctavan/express-validator#152]
When I use `req.assert(id, 'id is not valid mongoId').isMongoId();`.
Whether or not the input is a valid mongoId, `req.validationErrors()` always output an object like below.

**Valid mongoId**
`{ param: '55a267fe2cec3f8424b33faf'
msg: 'id is not valid mongoId',
value: undefined }`

**Invalid mongoId**
`{ param: '55a267fe2cec3f',
  msg: 'id is not valid mongoId',
  value: undefined }`

**Comment by rustybailey** [comment]
You are not using the `assert` correctly. `id` should be in quotes so that it will know to test the "id" key on your request object. Since you're passing in the id variable, it is looking for the '55a267fe2cec3f8424b33faf' key which doesn't exist (which is why the "value" is `undefined` in the error object). Please let me know if this helps.

**Comment by honglio** [comment]
@rustybailey Thank you! Put `id` in quote works.

**Comment by rustybailey** [comment]
Awesome!
