### ISSUE TITLE
sanitizeHeaders missing?

### ISSUE THREAD

**Issue by felixSchl** [ctavan/express-validator#177]
Is there any reason `sanitizeHeaders` does not exist? I am parsing a custom header from a string into a custom type, but I keep getting `undefined is not a function` when I call `req.sanitizeHeaders`.

**Comment by rustybailey** [comment]
Right now there is a `checkHeaders` function (which is currently undocumented) for validation purposes, but there doesn't seem to be a `sanitizeHeaders`. I know sanitizers haven't traditionally been as fleshed out as validators since that's not the primary function of this module. @ctavan, was there a specific reason this was omitted?

If not, we could probably add a `sanitizeHeaders`, but we would want to make sure we also document and add tests for `checkHeaders` and `sanitizeHeaders`. We would be open to pull requests for this.

**Comment by ctavan** [comment]
I cannot recall a specific reason, no. Probably it was just never needed and thus never implemented ;).

**Comment by rustybailey** [comment]
This feature was added in v2.18.0.
