### ISSUE TITLE
Invoke check() on any object?

### ISSUE THREAD

**Issue by JaniszM** [ctavan/express-validator#193]
Is it possible somehow to invoke `check()` function on any object? I have multipart object obtained by `formidable` lib and want to use this validator but as I understand `check()` and its aliases will search only in  `params, query, body` objects invoked on `req` object.

**Comment by aristidesfl** [comment]
If you want validate values outside of `req.body` you can use [validator.js](https://github.com/chriso/validator.js) which is the same without the middleware. 

If you want to use `express-validator`, and have your form-data inside `req.body` you can use [mutler](https://github.com/expressjs/multer) instead of formidable.

**Comment by rustybailey** [comment]
Thanks for the answer, @aristidesfl! To add to this, the validator library is exposed in this package, so you can access all those methods by doing:
``` js
var expressValidator = require('express-validator');
var validator = expressValidator.validator;
```

**Comment by JaniszM** [comment]
Thanks guys.
