### ISSUE TITLE
new param 'in' for schema validation

### ISSUE THREAD

**Issue by JaniszM** [ctavan/express-validator#206]
I'm facing with problems of checking request against schema at multiple places. Checking query params and express params for one endpoint using schema is problematic. Schema requires to have structure like {param: {}, param2: {} ...}. This mean currently you cannot have one schema for one endpoint if you want to check against more than one scope: e.g. check query and headers.

I think it would be nice to implement special field name 'in' that would be validated by check() method and delegate proper validation e.g. checkQuery(). Of course this field must me skipped during field validation.

One more, if param in schema is a function, then also should be skipped. Currently this leads to some strange behavior.

Proposal:
```
    var s = {
        "client-token": {
            in: "headers",
            "notEmpty": {
                "errorMessage": "Given param cannot be empty."
            },
            "errorMessage": "Missing argument."
        },
        "id": {
            in: "params",
            "notEmpty": {
                "errorMessage": "Given param cannot be empty."
            }
        },
        "authorization": {
            in: "query",
            "notEmpty": {
                "errorMessage": "Given param cannot be empty."
            }
        }
    };
```

Without this stuff you need to use a lot of schemas that becomes pointless to using schema ;x 

What do you think guys?

Or maybe there is already some solution that can work for me?

Edit: Ok, I did this fix already, I will prepare pull request today. And I see there is a oproblem with validating headers so I will skip this one.

Edit: all tests passing.

**Comment by JaniszM** [comment]
Hmm, guys, how to concribute your stuff? ;) I have 403 of course :( Let me know, I have prepared branch for this issue.

**Comment by rustybailey** [comment]
In order to contribute, fork this repo, create a branch, make your changes, and then create a pull request in Github. For more info, go here (https://guides.github.com/activities/contributing-to-open-source/) and scroll down to "Pull Request Pro Tips".

For this specific repo, whenever you make a pull request, make sure you have documented the fix or feature in the README and have written tests. Lastly, run `npm run travis-build` to make sure your code passes all tests. jshint, and jscs. 

Sounds like I should probably write a `Contributing.md`. Let me know if you have any questions.

**Comment by JaniszM** [comment]
Ok, thanks, so I need to fork it anyway ;)

**Comment by JaniszM** [comment]
Done, please review changes.

**Comment by rustybailey** [comment]
This enhancement is now in 2.20.1

**Comment by JaniszM** [comment]
Cool, thanks :)
