### ISSUE TITLE
how to show only one validation error message per field

### ISSUE THREAD

**Issue by grandcoder** [ctavan/express-validator#235]
I have a registration form and a user has to submit email address in the form (along with other fields). my validation rule for the email field with 'express-validator' is

`req.checkBody('email', 'Email field is required').notEmpty().isEmail().withMessage('Invalid email address');`

and I am using jade to print out the errors as (with bootstrap)

```
  if errors.length  
    .alert.alert-danger
      a.close(href='#', data-dismiss='alert', aria-label='close') ×
      for error in errors
         div=error.msg 
```

the above code print out all the form errors of the fields, now the problem is, if email field is empty, it shows two error messages 'Email field is required' and 'Invalid email address'

I want to evaluate the second validation isEmail() only if the email is not empty. If empty then it need to show only one error message 'Email field is required'. Is there any solution to this ?

**Comment by james-siteclick** [comment]
Maybe this will help - according to the docs if you specify:
var mappedErrors = req.validationErrors(true); 
You only get 1 error per field.

**Comment by srkimir** [comment]
@james-siteclick that will not help in this case, still both validations `isEmpty()` and `isEmail()` will be executed. `req.validationErrors(true)` will return only last error which will be something like:
```
{
  "email": {
    "param": "email",
    "msg": "Invalid email address"
  }
}
```
@grandcoder 
As it seems to me from source code this is not possible at the moment because regardless of validation status `true/false` all further validations will be executed. I will put `enhancement` label to this issue and will look into this in details as soon as possible.

**Comment by gustavohenke** [comment]
Hi everyone! The fix for this has finally landed in v3.0.0!

```js
req.getValidationResult().then( result => {
  var errors = result.useFirstErrorOnly().array(); // enjoy an array with no duplicated errors for any given parameter!
})
```

Do you prefer the old style of mapped errors? We've got you covered:

```js
req.getValidationResult().then( result => {
  var errors = result.useFirstErrorOnly().mapped();
})
```

**Comment by deveArt** [comment]
But it is NOT the same issue as break validation chain. When I want to use exist() validator there is no need to validate an empty field by other validators. Isn't it obvious ? And if the field is not empty I want see ALL possible errors ! But this lib can't do that unfortunately.

**Comment by gustavohenke** [comment]
Hi @deveArt!
Let's break your comment into parts:

> When I want to use exist() validator there is no need to validate an empty field by other validators. Isn't it obvious ?

The `exists()` validator was added as of v4. It's mainly a measure for users who simply want to check that a field *is present*. You can combine it with other validators as well, but it doesn't make much sense.

What does make sense though is to use `optional()`. Fields that are tagged as optional will not run thru any of the other validators. This behaviour remained the same since v2.

> And if the field is not empty I want see ALL possible errors ! But this lib can't do that unfortunately.

*It does*.
When v3 was first introduced, the `.array()` method in the validation result would return *all* errors by default. You could, however, combine it with `useFirstErrorOnly()` method, which would then skip all errors but the first one for each field.

v4 still allows you to do both when using the `array()` method of the validation result.

Thanks!

**Comment by Younell** [comment]
I have a situation where I should break the chain before passing to the next validation method:

    check('source')
        .isLength({ min: 1 }).withMessage('Required')
        .isMongoId()
        .custom(rules.existSource)

    // existSource will check if the id exist in sources collection and return true or false

If I send an empty source I get an error: 
> Cast to ObjectId failed for value "" at path "_id" for model "Source"

this error is throwing because the existSource validator expect a valid mongoID, I think it would be faster if the chain stopped at the first occurring error.

you can for example pass it as an option:

     const validator = require('express-validator');
     const check = validator.check({ StopValidationOnFirstError: true });

Thanks
