### ISSUE TITLE
Integer minimum with skip validation

### ISSUE THREAD

**Issue by darrais** [ctavan/express-validator#254]
I have an integer field to which I want to skip validation if the property is falsy. If not, the integer should be at least equal to 1. 

However, since I'm using the `optional()` method with the options `{ checkFalsy: true }`, if the value is equal to `0` validation never occurs.

` req.checkBody('number', 'Enter an integer number between 1 and ' + max)
       .optional({ checkFalsy: true }).isInt({ min: 1, max: max });`

**Comment by gustavohenke** [comment]
What values lesser than 1 are you testing?
I'm asking because `0` is a falsy value in JS. Therefore it'll probably pass the `#optional()` test.

**Comment by darrais** [comment]
Sorry, I edited my first comment. I'm having that problem exactly with a value equal to `0`.

**Comment by gustavohenke** [comment]
OK, the following snippet shows your issue in practice very well:
https://runkit.com/gustavohenke/5808a2a98e9f750014ec7d74

Therefore, the combination `0` and `checkFalsy: true` does not return errors because
- `req.body.number` key exists
- `0` is a falsy value

If you switch `checkFalsy` to `false`, then your validation will probably work.
For clarification, [this part of the docs](https://github.com/ctavan/express-validator#optional-input) describes the `checkFalsy` behavior and your issues with it:

> **By default, it only skips validation if the key does not exist on the request object.** If you want to skip validation based on the property being falsy (null, undefined, etc), you can pass in `{ checkFalsy: true }`.

Finally, this is the intended behavior. Let me know if you have further questions.
