### ISSUE TITLE
isAlpha 'uk-UA'

### ISSUE THREAD

**Issue by Fulminant** [ctavan/express-validator#270]
Can you update you version validator package?
Cause newest version support ukrainian locale.
https://github.com/chriso/validator.js/issues/584

**Comment by rustybailey** [comment]
@gustavohenke I glanced over this briefly a week or so ago. Looking at the changelog (https://github.com/chriso/validator.js/blob/master/CHANGELOG.md), in order to upgrade to v6+, we'll probably need to do a major version bump on our end. In that case, may be good to wrap this in with any other major version changes you've seen in PRs.

**Comment by gustavohenke** [comment]
Sure, I agree with you. I'll probably pack this upgrade with #269 and some other ideas I have before thinking about releasing v3.0.0.
