### ISSUE TITLE
Optional parameters

### ISSUE THREAD

**Issue by Abhimanyu310** [ctavan/express-validator#277]
I have a form that posts to the server with the field email. I want the validation such that, if the field is empty it should skip validation. But if the field is not empty, then it should check for a valid email. According to the github page, the below code should achieve this.

```
req.checkBody({
  'email': {
    optional: {
      options: {checkFalsy: true}
    },
    isEmail: {
      errorMessage: 'Invalid Email'
    }
  }
});
```

But, even when the field is empty, I get an error. Am I doing anything wrong?

**Comment by gustavohenke** [comment]
Hi! Sorry for the delay.
What is the version of express-validator you're using?

**Comment by Abhimanyu310** [comment]
@gustavohenke Version 2.20.10

**Comment by gustavohenke** [comment]
Alright then, I know what the problem is!
This is caused because of the way you're using the `options` key in schema validation with that lib version.

Previously, you needed to pass options as array.
Thanks to #191, when you're using a single option, there's no need to wrap that option in an array.

So, please update to v2.21.0 or wrap the option in an array, eg `[{ checkFalsy: true }]`

**Comment by victoramala** [comment]
where i provide this validation

**Comment by vitaliybilous** [comment]
in v4.1.0 I receive this error
```javascript
const schema =  {
  ...
  'data.minify' : {
    optional : true
  },
  ...
}
```
in console:
`UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot set property 'message' of undefined
`

**Comment by gustavohenke** [comment]
@vitaliybilous can you please provide further information, and open a new issue?

**Comment by vitaliybilous** [comment]
@gustavohenke I opened new issue #398
