### ISSUE TITLE
Execute validator sequential

### ISSUE THREAD

**Issue by williamdang1710** [ctavan/express-validator#322]
I have a validation schema like this:
```
req.check({
    'field': {
        notEmpty: {
            errorMessage: 'bla bla bla'
        },
        isMongoId: {
            errorMessage: 'bla bla bla bla bla'
        },
        isAccountId: {
            // this is a custom asynchronous validator 
            errorMessage: 'bla bla bla bla bla bla bla'
        }
    }
});
```
I want the validator 'isMongoId' kicks in only if 'notEmpty' is successfully pass. Thus, 'isAccountId' should be after 'isMongoId'.
As far as I know, express-validator does every validators in parralel. Is there a way that I can achieve this?

**Comment by gustavohenke** [comment]
> I want the validator 'isMongoId' kicks in only if 'notEmpty' is successfully pass. Thus, 'isAccountId' should be after 'isMongoId'.

This is not really possible because of the way objects iteration work, at least in V8/Node.js/Chrome.  
The order of iteration is not guaranteed - there's no such thing like "iterate by keys in the order they were specified" or "iterate by keys in their alphabetical order".

We could, however, apply this by specifying the schema as an array, which is something for express-validator v4 😃 

> As far as I know, express-validator does every validators in parralel.

There's no such thing in our codebase.

**Comment by gustavohenke** [comment]
Hello! [v4.0.0 has finally been released](https://github.com/ctavan/express-validator/releases/tag/v4.0.0).

The new `check` APIs will run validators within a given chain in sequence. This may resolve your problems, @williamdang1710.

Please check the README for complete docs, and also check the [upgrade guide](https://github.com/ctavan/express-validator/blob/v4.0.0/UPGRADE_GUIDE.md).
