### ISSUE TITLE
notEmpty vs Optional

### ISSUE THREAD

**Issue by sundriver** [ctavan/express-validator#334]
Hi there,
 Thanks for the great library. Could you let me know what am I doing wrong below.

function isRequired(isRequired:boolean){
 return { name : { optional: !isRequired } };
}

When I pass isRequired(true), the optional attribute should be false hence the field should be required. if the input doesn't have the name value, I want the request to fail but the validation let's the request go through. Could you let me know what am I doing wrong here ?

also, what is the difference between notEmpty and optional ? 

Thanks,

**Comment by gustavohenke** [comment]
Hello!
This issue is the same as #263, therefore I'm closing it.

> what is the difference between notEmpty and optional ?

- `notEmpty` validates that a value has a length of at least 1
- `optional` skips validation for a given key if it doesn't exist on the request object. With `checkFalsy: true`, the given key will have the validation skipped if its value is falsy (`false`, `null`, `0`, `undefined`, empty string)
