### ISSUE TITLE
Why deprecate `req.validationErrors`?

### ISSUE THREAD

**Issue by Flame2057** [ctavan/express-validator#368]
I really don't understand why you would do this? Now I have to run the async function `req.getValidationResult` in every route that takes in a body or query string... seriously? More callback hell? How is this an improvement?

**Comment by Flame2057** [comment]
Like could you at  least make a `req.getValidationResultSync` function or something, so we can get the result synchronously?

**Comment by Flame2057** [comment]
I don't see why you would **ever** want to get errors asynchronously.... people are gonna get the errors and if there are some, they will throw a status 500. They would not run their route code while they looked for errors in user input, that would just be stupid.

**Comment by Flame2057** [comment]
You people are ruining nodeJS.... this kind of crap is the reason nobody takes node seriously

**Comment by gustavohenke** [comment]
Hello!
Let's answer some of your points...

> I don't see why you would ever want to get errors asynchronously

What if you actually have async validators?

> seriously? More callback hell?

`async`/`await` is natively supported by Node since v7.8+.
This way you can have an async flow that looks as sync as true sync code.

> Like could you at least make a `req.getValidationResultSync` function or something, so we can get the result synchronously?

I'm not willing to add further methods to the request without a _really_ good reason.
v3.0.0 is out since December 2016. The deprecation notice has been visible in the README since then, but only now it's printed in the application logs.

It seems like you're okay with using deprecated methods, as long as they don't litter your logs.

> Why deprecate `req.validationErrors`?

The introduction of `req.getValidationResult()` _is_ an improvement over usage of `req.validationErrors()`/`req.asyncValidationErrors()`.

A few problems we had before:

### API Inconsistency
`req.validationErrors()` _returns_ the errors.
`req.asyncValidationErrors()` _throws_ the errors (in a promise).

### [Boolean trap](https://ariya.io/2011/08/hall-of-api-shame-boolean-trap)
Without previous knowledge of the API, would you understand that `req.validationErrors(true)` means "give me the errors as an object"? I'm pretty sure you wouldn't .

### Mapped errors = only last error
If you wanted to have the errors as objects, you could pass the `mapped` parameter to any of the functions.
But how do you like the object? Only the first error? All errors? No, the API returned the last one.
Making changes to this behaviour would be a breaking change anyway.

### `req.asyncValidationErrors()` throws an array
As I said before, this function _throws the errors_ - literally, if you're not using `mapped` parameter (to get them as an object), then an array is what you get.
This would make some people sad, as you can see here: #223

---

I'm aware that having to deal with async code is not always pleasant.
v4 is a plan I have to fix some of the footprints left behind by v3. You can already see some issues tagged with "Milestone: Version 4".
The idea of this future version is to play with functions composition (eg as inline middlewares), so there's no need to deal with validation _in_ your route handler.

In the meanwhile, if you want to change something, you can start by providing some API ideas, sending some PRs to fix stuff that really matter (#347, #331, #294), etc.

**Comment by Flame2057** [comment]
Node 8 doesn't even tell you where syntax errors are, it is not production ready
