### ISSUE TITLE
Custom validator to validate more than two or more fields 

### ISSUE THREAD

**Issue by noisytoken** [ctavan/express-validator#371]
My question is how do I write a custom validator to validate data from two or more fields at once. Documentation only mentions how to write custom validator for individual fields only.

**Comment by gustavohenke** [comment]
You're right, this is not possible at the moment, but thanks for the suggestion.

The best you could do is create a custom validator that takes the second field value as a param:

```js
app.use(expressValidator({
  customValidators: {
    areBothValid (value, otherParam) {
      return isValidSomehow(value) && isAlsoValidSomehow(otherParam);
    }
  }
}));
```

Please note that this will never mark that second field as invalid though :(

**Comment by gustavohenke** [comment]
Hello @noisytoken, [v4.0.0 has been released](https://github.com/ctavan/express-validator/releases/tag/v4.0.0), and it can help you fix your issue.

Since you never gave hint of whether what you wanted is what I mentioned above or not, I'll just tell you to go check [the README for complete docs](https://github.com/ctavan/express-validator/tree/v4.0.0) and the [upgrade guide for version 3 users](https://github.com/ctavan/express-validator/blob/v4.0.0/UPGRADE_GUIDE.md).

**Comment by kasymbayaman** [comment]
Hello @gustavohenke , so how this problem can be solved?
