### ISSUE TITLE
Validator prevents all requests from being processed

### ISSUE THREAD

**Issue by mtitolo** [ctavan/express-validator#374]
A few days ago I was adding express-validator to a new project and all requests stopped working. The server hangs. I've created a sample project that reproduces the issue: https://github.com/mtitolo/exp-val-err. This bug has been reproduced with node 6 and 8, and on multiple computers.

After some digging, I figured out the issue has something to do with [validator registration](https://github.com/ctavan/express-validator/blob/master/lib/express_validator.js#L226). If you put a breakpoint or log at the beginning of the function, it will continually get called preventing anything else from happening. No actual validations need to be performed for the bug to surface, registering the middleware is all it takes.

I'll update if I find a workaround other than not using this middleware.

**Comment by gustavohenke** [comment]
[You're adding the middleware _directly_](https://github.com/mtitolo/exp-val-err/blob/master/index.js#L24).

The return of the `express-validator` module is intended to be used as a factory function, so that you can pass custom validators/sanitizers or an error formatter:

```js
app.use(expressValidator());
```

Check the README for further info on how you could customize the middleware setup.
