### ISSUE TITLE
version 4 schema validation

### ISSUE THREAD

**Issue by gimox** [ctavan/express-validator#433]
any plan for schema validation on version 4 ? (not legacy)

**Comment by gustavohenke** [comment]
Adding back the same object-based validation is not within my plans for v4+.
At least until someone shows me a good reason to..

**Comment by Come2Daddy** [comment]
Validation without schema is now part of the route definition, that is a flaw in my opinion. I don't like redundancy, middleware approach is tricky and could lead to maintenance difficulties. With schemas, we can share validation through routes or approach them with Model pattern in mind.

**Comment by gustavohenke** [comment]
There's nothing preventing you to reuse the a group of middlewares, @Come2Daddy:

```js
// schemas.js
exports.person = [
  check('email').isEmail(),
  check('name').exists()
];

exports.article = [
  check('title').exists(),
  check('content').exists()
];

// routes.js
// Note you may create a user, an article, or even a guest article
// by passing the same article data + the guest name and email
const schemas = require('./schemas.js');
app.post('/user', schemas.person, check('password').isLength({ min: 5 }), routeHandler);
app.post('/article', schemas.article, routeHandler);
app.post('/guest-article', schemas.article, schemas.person, routeHandler);
```

**Comment by mtpultz** [comment]
In #452 I posted a question looking for an alternative to using schemas to abstract the validation logic out of the route handler so it can be contained within a single validation method that would invoke a validation chain, and handle the error response or continue onto the next middleware.

```
router.post('/examples/:id',
  exampleController.validate,
  // Now the controller doesn't have to consider validations (or catching an error) since they 
  // have been handled it just has to get down to business
  exampleController.create
);
```

**Comment by mtpultz** [comment]
@gustavohenke using the idea of reuse from your example above I created a gist that seems to do everything illustrated in my example.  

So in case it is useful for docs or leads to a better implementation of any kind I put it into a [gist](https://gist.github.com/mtpultz/45a28445a6e710008b9b92c82792122d).  Let me know what you think, but regardless it provides an example of abstracting the validations out of the route handler.

**Comment by JeffMatthews2** [comment]
This might be the thread I am looking for.  Are you discussing coming up with a means to define a validationChain and re-use it?  If not, I apologize.  I am trying to standardize validationChains for re-use in order to keep things easy to maintain and consistent.

An example context would be **users/registration** and **users/update**.  When validating a user-supplied name, the validation logic is only slightly different.  

When posting to **users/register**, we **always** need to check for the name against the database (putting aside standard stuff, like trim(), etc.).  However, when posting to **users/update**, we need to check for the name against the database **only if the user is changing his name** (for a system where all user's names must be unique).

I've tried the code below, only to find out that it will not compile because `req` is undefined.

```
const nameValidationChain = ( name, userName ) => {

	// Provides all validation of the value the user supplies for his name.
	//
	// name (required): the value the user supplies
	// userName (optional): the name of the currently-logged in user

	// returns: a validation chain.  

	 return check('name')

		.trim()

		.isLength( {min: 5, max: undefined } )
		.withMessage('Name must be at least 5 characters.')

		.custom( (name, {req}) => {
			if ( name.length >= 5 && userName ? name.toLowerCase().trim() !== userName.toLowerCase().trim() : true ) {
				// User changing his name.
				// Be sure someone else isn't using that name.
				return new Promise( (resolve, reject) => {
					User.getUserByName(name).then(user => {
						reject('This name has already been registered by another user.');
					}).catch( err => {
						resolve(true);
					});
				});
				return false;
			} else {
				return true;
			}
		}).withMessage('This name has already been registered by another user.'),

		sanitize('name').trim();
}

// Profile
router.post('/update', auth.ensureAuthenticated, [

        // replacing the long, nasty chain with simple notation
	nameValidationChain( req.body.name, req.user.name )

        ... etc.

// Register
router.post('/register', auth.ensureAuthenticated, [

        // replacing the long, nasty chain with simple notation
	nameValidationChain( req.body.name  )

        ... etc.

```

**Comment by gustavohenke** [comment]
Hey @JeffMatthews2,
Here are some tips on how to make your code work:
- `check('name')` is creating a validation chain to validate `name` wherever it is. This way you don't need to pass `req.body.name` when defining your routes
- `userName` can also be removed, as you're only using it within your custom validator. You have `req` there, so if `req.user` exists, you can use that 😉

**Comment by JeffMatthews2** [comment]
Sure enough, it works!  @gustavohenke, I have a question that will likely help me understand and use the tools better.  In my nameValidationChain, when I have `.custom( (name, {req}) => {`, how is it able to work?  Is execution of the code delayed until the post hits its callback?  The concept of "middleware" is still settling in with me.

What really baffles me is that req is not defined in the **post** code until after it reaches the final callback with `{req, res, next}`.  That's why I was getting an undefined error when calling `nameValidationChain(req.body.name, req.user.name)`.  

So, how does the revised (per your instruction) nameValidationChain tie into the process?  How is the flow occurring such that I am able to access **req** there?  On its face, I get the impression that the validationChain is middleware and that it executes prior to the post's final callback.  However, operationally, due to the undefined error, I don't think this is happening.

**Comment by srkimir** [comment]
@gustavohenke 
> Adding back the same object-based validation is not within my plans for v4+.
At least until someone shows me a good reason to.

I would highly disagree with your comment, schema in my opinion provides very straight forward and readable request data validation. Schema validation is very common way of validating stuff, the main reason why i'm using this library is because of schemas.

```
module.exports = validationSchema => {
  return (req, res, next) => {
    req.asyncValidationErrors()
    .then(next)
    .catch(validationErrors => {
       /**
         * Respond back before touching route logic
         */
    })
  }
}
    
```

Instead of choosing to put schema validation in legacy API it would be far more better that validation is decoupled from `req` object entirely, so devs could use same API for validation for examples RabbitMQ messages or whatever JS object.

**Comment by gustavohenke** [comment]
Hey @srkimir,
I acknowledge that this feature is a very desired one, and would like to close this issue by making the folks here happy.

What's your reason for preferring schemas? Is it because of the no-function-calls validation style?

---

And, regarding this:
> Instead of choosing to put schema validation in legacy API it would be far more better that validation is decoupled from req object entirely, so devs could use same API for validation for examples RabbitMQ messages or whatever JS object.

...do you mean that express-validator should no longer be express-bound? 😄

**Comment by srkimir** [comment]
@gustavohenke 
Hi Gustavo, thanks for fast response. Yes one of the reasons are no-function-calls as you are saying, and at least to me seems very readable and pretty straightforward when i'm using validations with schema.

> That's ambitious.
true 😄 
Not to decoupled with express entirely, rather if validation schema is already there, to be reused in someway if it is possible to validate something that does not have anything to do with `request`, it would be nice feature if it is possible.

**Comment by mohsincynexis** [comment]
Hi, there my schema validations are not working. As said by you that custom validation should return a promise and that's what I am doing but still, it's not working. here is my code.
`email: {
            errorMessage: 'Please enter a valid email address',
            isEmail : true,
            trim: true,
            custom: {
                options: (value) => {
                
                    if(value)
                    {
                        return new Promise(function (resolve, reject) {

                            dns_validate_email.validEmail(value, function(valid) {
                                console.log('valid:'+valid);
                                if (valid) {
                                    resolve(value)
                                }else{
                                    reject('Not a valid email');
                                }
                            });

                        }).then(function (email) {
                           
                            User.findBy('email', email, function (err, result) {
                                console.log(typeof result.length);
                                console.log(result.length);
                                return result.length===0?true:false;
                            });
                            
                        })/*.then(function (result) {
                            
                            console.log('leee' + result.length);
                            if(result.length==0){
                                //console.log('record not found');
                                return true;
                            }else{
                                //console.log('record found');
                                return false;
                            }
                        })*/
                    }

                },
                errorMessage: 'This email is already in use',
            }
        },`
Guys please help me.

**Comment by mohsincynexis** [comment]
Thanks a lot, gustavohenke,

So it means every time I perform an async operation I have to return a promise?

**Comment by mohsincynexis** [comment]
Also Please help in one more point that when I reject with an error message, that message does not show up instead a default one shows up used for the custom validator. So in my case when an email is not valid from DNS then it should display "Not a valid email" but it always displays "This email is already in use"

Please Please guide.

**Comment by mohsincynexis** [comment]
Hello there,

Can any one of you please please help me on this?
