### ISSUE TITLE
Is it possible to do the validation in a separate file and not inline in the route?

### ISSUE THREAD

**Issue by gkatsanos** [ctavan/express-validator#449]
I am using express-validator to validate the Request body. I wanted to abstract validation in a separate JS partial/import and not have it inline in my routes.

Here's what I created:

```js
// routes

const controller = require('../controllers/auth.controller');
const validate = require('../validations/auth.validation');
router.route('/register')
  .post(validate.register, controller.register);


/**** auth.validation.js *****/

const { check, validationResult } = require('express-validator/check');

exports.register = (req, res, next) => {
  check('email').isEmail().withMessage('must be a valid email');
  const errors = validationResult(req);
  if (!errors.isEmpty()) {
    return res.status(422).json({ errors: errors.mapped() });
  }
  return next();
};
```
I get
```
RangeError: Invalid status code: undefined
    at ServerResponse.writeHead (_http_server.js:188:11)
```

**Comment by gustavohenke** [comment]
Hey @gkatsanos,
The correct way to use express-validator would be to use it as a middleware when defining your express routes, eg:

```js
// auth.validation.js
exports.register = [
  check('email').isEmail(),
  (req, res, next) => { /* the rest of the existing function */ }
];
```

...otherwise, the validations will never run.

Also, you may be doing something wrong inside your routes, as Node's http module is complaining about an undefined status code. This is unrelated to express-validator, so I recommend you to use StackOverflow in case you need more help finding the issue.

**Comment by gkatsanos** [comment]
Thank you @gustavohenke , please allow me to take advantage of your helpfulness :) with a follow-up question which I'll try to make more `express-validator` specific.
Regarding throwing and catching the error with `validationResult(req).throw();` if it possible to do that WITHIN the middleware validation function (so that it doesn't reach the final controller logic at all?) (I guess it's not possible because the express-validator seems to require to be in array format?)

**Comment by gustavohenke** [comment]
Answer to both questions: yes, you can!

Now, specific to 1: you may want to create a reusable validation result handler.

```js
exports.validationResultHandler = (req, res, next) => {
  try {
    validationResult(req).throw();
    next();
  } catch (e) {
    res.status(422).json({ errors: e.mapped() });
  }
};
```

express-validator v4 is tailored to use the most out of express; you may specify the validators using [any combination that is accepted by express](http://expressjs.com/en/4x/api.html#app.METHOD) - list of array of middlewares, a list of middlewares, array of middlewares, a single middleware, etc. You don't need to specify using only arrays.

And, regarding 2: you can use a function called [`.formatWith()`](https://github.com/ctavan/express-validator#formatwithformatter) on the validation result object.

**Comment by gkatsanos** [comment]
for number 1, I was asking if I can do something like : 

```js
router.route('/register')
  .post(validate.register, controller.register);
```
with `validate.register` being: 

```js
exports.register = (req, res, next) => {
  check('email').isEmail().withMessage('must be a valid email');
  check('password').isLength({ min: 4 }).withMessage('passwd 4 chars long!');
  try {
    validationResult(req).throw();
    next();
  } catch (err) {
    res.status(422).json({ errors: err.mapped() });
  }
};
```



because I get `err: TypeError: Cannot Read property 'length' of undefined at Object.obj.throw`

**Comment by gustavohenke** [comment]
While you *can* do that, it should be a little different, what makes specifying as an array *a lot better*.

Your error is caused because at the point you call `validationResult(req)`, no validators ran (yes, I know this can be handled by express-validator!).

When you use `check(...)` or any of its methods, you're getting a middleware as a result.
This means a function which takes `req`, `res` and `next`! So your code would end up like this:

```js
check('email').isEmail().withMessage('must be a valid email')(req, res, err => {
    if (err) {
        return next(err);
    }

    check('password').isLength({ min: 4 }).withMessage('passwd 4 chars long!')(req, res, err => {
        if (err) {
            return next(err);
        }

        try {
            validationResult(req).throw();
            next();
        } catch (err) {
            res.status(422).json({ errors: err.mapped() });
        }
    });
})
```

You see? It's a callback hell!

If you pass the result of `check(...)`/its methods to express, the code will look better.

**Comment by gkatsanos** [comment]
Thank you :) indeed the array then looks much much better!: 

```js
exports.register = [
  check('email').isEmail().withMessage('must be a valid email'),
  check('password').isLength({ min: 4 }).withMessage('passwd 4 chars long!'),
];
```

**Comment by gkatsanos** [comment]
hey @gustavohenke sorry to come back on this but my solution above isn't working and I was wondering what I am doing wrong?
my route is:
```js
router.route('/login')
  .post(validate.login, controller.login);
```
and validate.login is: 
```
exports.login = [
  check('email').isEmail().withMessage('must be a valid email'),
  check('password').isLength({ min: 4 }).withMessage('passwd 4 chars long!'),
];
```

**Comment by gkatsanos** [comment]
Hello, coming back to this as I resumed on this project.
Even though my validation happens, the custom message isn't passed / returned.. 
Here's the code:

`route`
```
router.route('/register')
  .post(validate.register, controller.register);
```

`validate.register`
```
exports.register = [
  check('email').isEmail().withMessage('must be a valid email'),
  check('password').isLength({ min: 4 }).withMessage('passwd 4 chars long!'),
];
```

and the `controller.register`
```
exports.register = async (req, res, next) => {
  try {
    const user = new User(req.body);
    const token = generateTokenResponse(user, user.token());
    const userTransformed = user.transform();
    user.tokens.push({ kind: 'jwt', token });
    user.activationId = uuidv1();
    await user.save();
    res.status(httpStatus.CREATED);
    sendValidationEmail(user.activationId);
    return res.json({ user: userTransformed });
  } catch (err) {
    return next(err, req, res, next);
  }
};
```

So when I make a bad request (short password for example), I get
```
{
    "statusCode": 422,
    "error": "Unprocessable Entity",
    "message": "User validation failed: password: Path `password` (`123`) is shorter than the minimum allowed length (4)."
}
```

and not my "withMessage" custom string..

**Comment by gustavohenke** [comment]
You don't seem to be handling the validation errors at all -- you need to call `validationResult(req)` and then do something with the [Validation Result API](https://express-validator.github.io/docs/validation-result-api.html).

**Comment by gkatsanos** [comment]
When I tried `validationResult(req).throw()`, the custom messages were still not included in the object caught in my `catch() { {}`

**Comment by gkatsanos** [comment]
all good, the information was there but I needed to use .mapped to format the object properly.

**Comment by morph85** [comment]
I managed to find out a better way to do it, by using "body" instead of "check".

check out these two links:
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_genre_form

`
// validator.js
const { /* check, */body } = require('express-validator/check')
module.exports = {
  email: body('email').isEmail().withMessage('Invalid email'),
  password: body('password').isLength({ min: 8 }).withMessage('Invalid password')
}

// route.js
app.post('/signup', controller.signup)

// controller.js
const { validationResult } = require('express-validator/check')
module.exports = {
  signup: [ // <- this operator is important so that you can include multiple operations
    v.email,
    v.password,

    (req, res) => {
      let errors = validationResult(req).formatWith(v.errorFormatter)
      if (!errors.isEmpty()) {
        return res.status(400).json(errors.array())
      }

      // your operation here
    }
  ]
}
`
