### ISSUE TITLE
.isBoolean not working

### ISSUE THREAD

**Issue by poisons77** [ctavan/express-validator#456]
Hi, I'm submitting a form through post method, but submitting a checkbox fails in validating it.

This is the code in the post route
`req.checkBody('agreeTerms', 'You\'ve to accept Terms&Conditions').isBoolean();`

The `console.log(req.body.agreeTerms);` return the "_on_" value but the function _checkBody_ continues to throw the error

**Comment by gustavohenke** [comment]
[The source of the `isBoolean`](https://github.com/chriso/validator.js/blob/8.2.0/src/lib/isBoolean.js) for validator v8.2.0 tells me that the only acceptable values are `true`, `false`, `1` and `0`.

You should work your checkbox so that it sends one of the accepted values, or open an issue in the validator repository requesting such change in `isBoolean` validator.
