### ISSUE TITLE
validator.js throws an error when user passes in an array value

### ISSUE THREAD

**Issue by codynguyen** [ctavan/express-validator#463]
Hi, I'm having this problem where validator.js throws `This library (validator.js) validates strings only` when user passes in an array value in the query.

Query: `mydomain.com/some/path?new=true&new=true`
Router code:

```
router.get('/some/path', check('new').isBoolean(),
function(req, res, next) {
  // Some code
})
```

The data type for `new` is Boolean in our API docs. If user tries to pass in an array like this, we just want to return a 400 error, not crashing the whole server.

I know the error is thrown by the validator.js lib, but is there any safe way to prevent it from express-validator, or maybe catch the error and handle it ourselves with the new express-validator API? 

Thank you.

**Comment by nkalvi** [comment]
Same error with `sanitize` etc. when used with checkboxes having the same name since multiple selections will result in an array:
i.e. `req.sanitize('checkbox')` works fine with single selection but fails with multiple, as `req.body.checkbox` returns a `string` for single selection and an `array` for multiple.

**Comment by gustavohenke** [comment]
Do you guys have any suggestion on what to do in these cases?
I guess the correct behaviour is to validate/sanitise all fields the same way. See related issue: #331

Anyway, whatever direction we head to will imply a breaking change.

**Comment by VaibhavAjayGupta** [comment]
@gustavohenke @codynguyen @nkalvi  I think wildcards(*) takes care of an array value.
I have successfully achieved the desired functionality just by using the wildcards(*).
https://github.com/mdn/express-locallibrary-tutorial/pull/31

**Comment by nkalvi** [comment]
@VaibhavAjayGupta Thank you. I'll check it out later.

**Comment by gustavohenke** [comment]
What express-validator are you guys using??
Current master code will indeed fail the validation, but not with `This library (validator.js) validates strings only` as reported by the OP.

**Comment by VaibhavAjayGupta** [comment]
I am using express-validator v4. What i did was added a middleware before validation that will convert the feild value (feild i am using wildcard on) to an array if it's value is not an array that was for a case for checkbox input problem.
Solution for OP problem can be to use a middleware to check type of value if an array return 400 instead of proceeding with validation.
