### ISSUE TITLE
unexpected result of matchedData() when using oneOf()

### ISSUE THREAD

**Issue by pkyeck** [ctavan/express-validator#482]
I'm trying to validate the token I pass to my REST endpoint. It could be passed in the HTTP headers , a cookie or as a POST parameter. So I'm checking like this:

```javascript
oneOf(
  [
    header('Authorization')
      .trim()
      .matches(/Token([abcdef0-9]{40})/i),

    body('token')
      .trim()
      .matches(/[abcdef0-9]{40}/i),

    cookie('cookiename')
      .trim()
      .matches(/[abcdef0-9]{40}/i),
  ],
  'token is missing'
),
```

Now I was expecting the result of `matchedData(req)` to only include the one value that was validated correctly but the other two are in there as well (as `undefined`). Is this expected?

And it would be great if we could expose the result under the same name. I don't want to get `authorization`, `token` or `cookiename` but just e.g. `token` no matter which of these was set.

**Comment by gustavohenke** [comment]
Hello @pkyeck! Thanks for using express-validator.
You have two different questions, so let's break them down into smaller pieces:

> I was expecting the result of matchedData(req) to only include the one value that was validated correctly but the other two are in there as well (as undefined). Is this expected?

Currently, [the tests don't say a thing about optional data](https://github.com/ctavan/express-validator/blob/v4.3.0/filter/matched-data.spec.js) (at least that's what I got from quickly going thru it), what is a shame!
But can you try using `onlyValidData` option? It should work.

> And it would be great if we could expose the result under the same name. I don't want to get authorization, token or cookiename but just e.g. token no matter which of these was set.

Given those are within `oneOf`, this is probably acceptable, but I'm not sure how I would go about it.
Would probably have to add a few more options to make it work with most scenarios.

Otherwise, this is quite easy to achieve in user-land.

**Comment by pkyeck** [comment]
I'm already using the `onlyValidData` option - the `undefined` values are in there nonetheless.

For the second part: yep, did this in userland.

**Comment by gustavohenke** [comment]
Hey @pkyeck, I would like to fix this for the next release (there's a good backlog of changes for a v5.0.0).

Are you up for a challenge? I began by adding a failing test in #506 -- if you have ideas, or would like to tackle this yourself, feel free to let me know!

**Comment by pkyeck** [comment]
was away from the computer the last couple of days. but thanks for fixing this!!
